# Sortify X v1.0
VERSION=1
INTERVAL=21600
SCHEDULE=boot
SCHEDULE_FROM=
SCHEDULE_TO=
WATCH_DIRS=/sdcard/Download
PAUSED_UNTIL=0
STOPPED=false
SORTING=false
CAT_DOCUMENTS=true
CAT_IMAGES=true
CAT_AUDIO=true
CAT_VIDEOS=true
CAT_ARCHIVES=true
CAT_APPS=true
CAT_CODE=true
CAT_DUPLICATES=true
CAT_OTHERS=true
EXT_DOCUMENTS=
EXT_IMAGES=
EXT_AUDIO=
EXT_VIDEOS=
EXT_ARCHIVES=
EXT_APPS=
EXT_CODE=
EXCLUDE_EXTENSIONS=
EXCLUDE_FILES=
